### ISSUE TITLE
Registering a suspend functional-style listener Velocity

### ISSUE THREAD

**Issue by ChimpGamer** [Shynixn/MCCoroutine#107]
Would it be possible to add a suspend method for the registering functional-style listener?
An example of the non suspend method: https://docs.papermc.io/velocity/dev/event-api#registering-a-functional-style-listener

Source code: 
- https://github.com/PaperMC/Velocity/blob/dev/3.0.0/api/src/main/java/com/velocitypowered/api/event/EventManager.java#L35
- https://github.com/PaperMC/Velocity/blob/dev/3.0.0/api/src/main/java/com/velocitypowered/api/event/EventManager.java#L49
- https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/event/VelocityEventManager.java#L351

I hope I provided enough information for you to work with.

**Comment by Shynixn** [comment]
Sure, this can be added.

**Comment by Shynixn** [comment]
Has been added to 2.14. See https://github.com/Shynixn/MCCoroutine/blob/master/mccoroutine-velocity-sample/src/main/java/com/github/shynixn/mccoroutine/velocity/MCCoroutineSamplePlugin.kt
