### ISSUE TITLE
Deadlock when using `runBlocking(Dispatchers.Minecraft)`

### ISSUE THREAD

**Issue by CrushedPixel** [Shynixn/MCCoroutine#27]
I'm not using this library directly, but am following the patterns you described in your initial README before this became an actual library.

This is my Minecraft dispatcher:

```kotlin
private class MinecraftCoroutineDispatcher : CoroutineDispatcher() {

    /** Dispatches the coroutine on the main server thread. */
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        if (Bukkit.isPrimaryThread()) {
            block.run()
        } else {
            // this directly calls the bukkit scheduler internally, no magic here
            BukkitExecutor.schedule(action = block::run)
        }
    }
}

/** A coroutine dispatcher that is confined to the Minecraft server thread. */
public val Dispatchers.Minecraft: CoroutineContext by lazy { MinecraftCoroutineDispatcher() }
```

This is all nice and dandy, and harnessing the power of Coroutines is truly a joy!
Unfortunately, there's a deadlock situation that I can't figure out how to fix.

Imagine the following code:
```kotlin
runBlocking(Dispatchers.Minecraft) {
    // do something on the MC thread...

    withContext(Dispatchers.IO) {
        // some file I/O
    }

    // handle the result on the MC thread
}
```

This will deadlock when switching context back to `Dispatchers.Minecraft`, as the Bukkit thread is blocked (thanks to `runBlocking`), which means that the Bukkit scheduler will never get to tick and execute the `Runnable`.

Unfortunately, in some cases, writing code like this is the most idiomatic thing to do - in my plugin's `onEnable`, I want to wait for the execution of a suspending function that switches between the I/O and Minecraft dispatcher a few times. However, the switching will deadlock if we use `runBlocking` for the aforementioned reasons.

Do you know of a solution to this issue? Is there a way to detect whether the primary thread is blocked, allowing us to execute code without fear of concurrency issues?

Thanks in advance!

**Comment by Shynixn** [comment]
Hi, the initial README is still present in this repository [Article.md](https://github.com/Shynixn/MCCoroutine/blob/master/ARTICLE.md) and it's perfectly fine for me to discuss this topic eventhough you are not directly using it. 

Coroutines have made our lives a lot of easier and I wholeheartedly agree that they are a joy. :)

#### So now let's get technically:

First of all, I did not know about that deadlock case. Actually, I have never run into it as **I do not use ``runBlocking`` anywhere** in my plugins. There is only 1 particular case in a production Plugin.jar file where it might be interesting to use it (onDisable) but I'll write another comment for that if you are interested in it.

One of the big advantages of coroutines is that a thread can do other "work" in the background and does not block which would happen if we use ``Thread.sleep(..)`` in Kotlin. If we use ``runblocking``, we loose that advantage. At first, we may not notice that but if a coroutine dispatcher uses a threadpool in the background with a fixed number of threads, it eventually blocks all threads which can end up in a deadlock. 

Regarding your enable() case. Can you please clarify why it is necessarry to run ``runBlocking`` in your ``onEnable()`` function? As far as I know there is no reason why the server should wait until your plugin is completely initialized. The simplest way  to switch to a suspend coroutine scope is using GlobalScope.

```kotlin
fun onEnabled(){
sout("1")
GlobalScope.launch(Dispatchers.minecraft) { 
    sout("2")
    withContext(Dispatchers.IO) {
      sout("3")
    }
   sout("5")
 } 
 sout("4")
}

// Output Order
"1"
"2"
"4"
"3"
"5"
```

This does not block any threads. 

#### Advertisement for my library

* However, please notice that my initial article did not talk about ``coroutine scopes`` which is a topic you should not underestimate as there are child scopes and states you can accidentally enter when a scope "fails" (throws an exception). In Android development, you come accross ViewModelScopes for example.
* MCCoroutine launches all coroutines you launch in its own scope which are childs of a plugin level coroutine scope.
```kotlin
plugin.launch(...) {

}
```
This means mccoroutine safely stops all of your launched coroutines on plugin reload which takes some effort to implement on your own. If you still not decide to use it, I recommend you to take a look at the implementation of the scopes in my library as they are essentially when running a production level plugin.

**Comment by CrushedPixel** [comment]
Thanks for your detailed answer! I am familiar with `CoroutineScope` and structured concurrency, and do use it in cases where we need to ensure tasks finish executing before the JVM exits.
I agree that `runBlocking` should be used sparingly, but in very few cases it makes sense to do so, IMHO - later lines of code in `onEnable` depend on a `suspend fun` being finished. While this may not be ideal practice for public plugins, our plugins are used only internally for MC Championship :)

In the meantime, I've found a solution that allows us to use `runBlocking` with the Minecraft Dispatcher. It's not the prettiest solution, but it works, and I prefer this over not being able to use `runBlocking`, because in some cases the most elegant solution is just to use it.

Enjoy:
```kotlin
private class MinecraftCoroutineDispatcher : CoroutineDispatcher() {

    @InternalCoroutinesApi
    override fun isDispatchNeeded(context: CoroutineContext): Boolean {
        if (Bukkit.isPrimaryThread()) return false

        // Check if the primary server thread is blocked during the execution of this coroutine.
        // If it is, using the Bukkit scheduler would cause a deadlock, as scheduled tasks
        // are executed at the end of the tick, which requires the server thread to be running.

        // To detect whether the server thread is blocked, we traverse the hierarchy of Jobs upwards
        // to check if there's a coroutine running in a [runBlocking] context.
        // If so, we don't dispatch, causing the action to be executed on the current thread.
        // As the primary thread is locked, this has no thread-safety implications with regards to
        // the Bukkit API.

        var job: Job? = context[Job]
        while (job != null) {
            if (job.javaClass == Class.forName("kotlinx.coroutines.BlockingCoroutine")) {
                // we found a coroutine spawned via runBlocking - check whether it blocks the
                // primary server thread using the same logic as [CraftServer.isPrimaryThread]
                val blockedThread = Reflect.on(job).field("blockedThread").get<Thread>()
                if (blockedThread == MinecraftServer.getServer().serverThread ||
                    blockedThread == MinecraftServer.getServer().shutdownThread ||
                    blockedThread is TickThread) {
                    return false
                }
            }

            if (AbstractCoroutine::class.java.isAssignableFrom(job.javaClass)) {
                // traverse context hierarchy upwards
                job = Reflect.on(job).field("parentContext").get<CoroutineContext>()[Job]
            } else {
                throw UnsupportedOperationException("Can't handle jobs of type ${job.javaClass}")
            }
        }

        return true
    }

    /** Dispatches the coroutine on the main server thread. */
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        BukkitExecutor.schedule(action = block::run)
    }
}

```

**Comment by Shynixn** [comment]
Thank you! I'll evaluate if it makes sense to add this to the library.
