### ISSUE TITLE
Bundle sources with maven release

### ISSUE THREAD

**Issue by AllanWang** [Shynixn/MCCoroutine#28]
I don't see what's done differently with your build gradle, but it seems like sources are not bundled together in through maven. When navigating the code, IntelliJ uses decompiled `.class` files rather than actual sources, so users won't be able to navigate through the code.

**Comment by Shynixn** [comment]
It really seems like that the published sources are not present in the -sources.jar files.

https://repo1.maven.org/maven2/com/github/shynixn/mccoroutine/mccoroutine-bukkit-api/1.1.0/
