### ISSUE TITLE
Sponge API-8?

### ISSUE THREAD

**Issue by HoshiKurama** [Shynixn/MCCoroutine#41]
Hey there! I'm a huge fan of your library! I use it in my plugin TicketManager, and it's now an integral part of the plugin! Currently my plugin is written for both Paper and Spigot, but I eventually want to create a Sponge version too. However, I noticed that the library is written for Sponge API-7. Do you have any plans to write an MCCoroutine version for Sponge API-8?

**Comment by Shynixn** [comment]
Thank you :) 
I don't have any plans regarding Sponge as the implementation of their rework is not stable yet. MCCoroutine builds against the server implementation (not just the API) in some parts (manipulating events) and there may be breaking changes on the side of Sponge.

I'll consider it once a stable server implementation (SpongeForge?) is available. Once that happens, you are free to open another ticket on this repository and I'll take a look at it.

**Comment by HoshiKurama** [comment]
Will do, thanks!
