### ISSUE TITLE
Option to call suspending events consecutively

### ISSUE THREAD

**Issue by nathanfranke** [Shynixn/MCCoroutine#51]
I am using events to manage my players' prefixes. However, if multiple prefixes are added in the events, ordering is very important.

In my situation, I am adding the player's rank first, then a color after it.

```kt
// Lowest priority - rank should be added before other prefixes.
@EventHandler(priority = EventPriority.LOWEST)
suspend fun rankOnPlayerPrefixUpdate(event: PlayerPrefixUpdateEvent) {
	delay(500.milliseconds) // Fetch rank from database

	event.prefixes.add(Component.text("[Rank] "))
}

// Highest priority - color should be added after other prefixes.
@EventHandler(priority = EventPriority.HIGHEST)
fun rankOnPlayerPrefixUpdate(event: PlayerPrefixUpdateEvent) {
	event.prefixes.add(Component.text("[Color] "))
}
```

```kt
// Update player's prefix with an event.
val event = PlayerPrefixUpdateEvent(player, mutableListOf())
server.pluginManager.callSuspendingEvent(event, this).joinAll()

println(event.prefixes) // '[Color] [Rank] '
```

Even though the rank event is being called first, its prefix is appended last because of the delay. There should be an option in `callSuspendingEvent` to wait for each suspending event before continuing to the next one.

Workarounds: 
- `runBlocking` fixes the ordering issue but misuses coroutines.
- Using `add(0, ...)` to explicitly prepend the prefix works, but is messy and only fixes this specific case.

**Comment by Shynixn** [comment]
I think you have a valid point here. 

Suspending events should run concurrently per default like do now but executing them consecutively is a valid usecase too. As I do actually have access to the listener/method ordering, it should not be a problem at all to introduce that.

My proposal would be to add an overload to the ``callSuspendingEvent`` as follow:

```kotlin
enum class EventExecutionType {
 Consecutive,
 Concurrent
}

fun callSuspendingEvent(event: Event, plugin: Plugin, executionType : EventExecutionType) : Collection<Job>{
  // ...
}

fun callSuspendingEvent(event: Event, plugin: Plugin) : Collection<Job>{
  return callSuspendingEvent(event, plugin, EventExecutionType.Concurrent)
}

```
The collection of jobs would be a single job when running it in Consecutive mode.


What's your opinion on that @nathanfranke ?

**Comment by nathanfranke** [comment]
That looks great to me

**Comment by nathanfranke** [comment]
Just tested and works amazing! Thanks for implementing this.

**Comment by Shynixn** [comment]
You are welcome! Leave a star if you like this project.
