### ISSUE TITLE
Allow Sentry to capture exceptions

### ISSUE THREAD

**Issue by keyute** [Shynixn/MCCoroutine#52]
Exceptions are captured and logged into console, requiring a handler to be added to the logger. Allow Sentry to capture these exceptions by adding a configuration value which will not handle these exceptions if set to true.

**Comment by keyute** [comment]
An alternative would be to call a ServerExceptionEvent so that these exceptions can be easily captured

**Comment by Shynixn** [comment]
I think exception handling is not as good as it could be. Exceptions are consumed and logged right now but propagating them from inner coroutinesScopes is missing.

This feature should definetly be added but I still need to think about it a way more. Something along the official docs: https://kotlinlang.org/docs/exception-handling.html

**Comment by Shynixn** [comment]
Custom logging is implemented in 2.0.0. 
See: https://shynixn.github.io/MCCoroutine/wiki/site/exception/
