### ISSUE TITLE
How can I plugin.launch{} on Velocity?

### ISSUE THREAD

**Issue by borodin0v** [Shynixn/MCCoroutine#65]
I ran into an issue where I need to do some work with a function like this:
`fun Audience.susMsg(message: Component) = plugin.launch {}`
I can't because Velocity plugins don't have any sort of superclasses.

**Comment by borodin0v** [comment]
So, I got it working by @Inject-ing a PluginContainer and then launching from it.

**Comment by Shynixn** [comment]
Yes, injecting PluginContainer is the correct way to do this.
