### ISSUE TITLE
SuspendingTabCompleter missing default support

### ISSUE THREAD

**Issue by Yomanz** [Shynixn/MCCoroutine#76]
The `SuspendingTabCompleter` doesn't have the same level of support as the regular `TabCompleter` provided in Paper.

You can return `null` to the `TabCompleter` to allow it to fall back to the default command executor but the signature for `SuspendingTabCompleter.onTabComplete` is:
 ```kotlin
suspend fun onTabComplete(
        sender: CommandSender,
        command: Command,
        alias: String,
        args: Array<out String>
    ): List<String>
```

compared to `TabCompleter.onTabComplete`
```java
@Nullable
public List<String> onTabComplete(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args);
```

**Comment by Shynixn** [comment]
That's true, thanks for reporting this. 
Hm... the only is that simply changing this is a breaking change for existing plugins using this feature. I may even need to do a major version change.

**Comment by Yomanz** [comment]
Thanks for sorting this so quickly :)
