### ISSUE TITLE
Deadlock when joining a job switching context to minecraft scope while plugin is disabled

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/MCCoroutine#82]
Notes:
* Only occurs when you try to join a job using ``runBlocking`` in ``onDisable``.
* Looking for hacktoberfest contributors.

How to fix:
* Add a ``plugin.isEnabled`` check to `` isDispatchNeeded`` in ``com.github.shynixn.mccoroutine.bukkit.dispatcher.MinecraftCoroutineDispatcher`` and ``com.github.shynixn.mccoroutine.bukkit.dispatcher.AsyncCoroutineDispatcher`` 
* Remove ``if (!plugin.isEnabled)`` check in ``dispatch`` from those files

**Comment by Jupiops** [comment]
Can I work on this?

**Comment by Shynixn** [comment]
Sure
