### ISSUE TITLE
Support of Minestom

### ISSUE THREAD

**Issue by Distractic** [Shynixn/MCCoroutine#91]
Can you add support for [Minestom](https://minestom.net/) game server ?

**Comment by Shynixn** [comment]
Yes, I can do that. 

After reading the wiki/javadocs of Minestom, it makes sense to implement MCCoroutine as a library for the following things
* Acquirable API
* Listeners
* Commands

However, I am not sure how to implement ``plugin.launch {}`` as there is no "plugin instance" in Minestom. Do you have an idea where to add the coroutine ``launch`` function?

**Comment by Tofaa2** [comment]
> Yes, I can do that.
> 
> After reading the wiki/javadocs of Minestom, it makes sense to implement MCCoroutine as a library for the following things
> 
> * Acquirable API
> * Listeners
> * Commands
> 
> However, I am not sure how to implement `plugin.launch {}` as there is no "plugin instance" in Minestom. Do you have an idea where to add the coroutine `launch` function?

Saw your post on the Minestom discord server, I'm not sure exactly what you're referring to as plugin.launch {} but if you mean generic Java Plugins then Minestom has an extension system that contains initialize() and terminate()

**Comment by Shynixn** [comment]
Thanks. MCCoroutine is designed to offer a custom coroutine scope for minecraft server frameworks which have a concept of "plugins". Minestom seems to have ``Extension`` but this may not be used if you directly modify the Minestom server software. 

I'll think about it and click through the Minestom source code.

**Comment by Shynixn** [comment]
Minestom support has been implemented.
