### ISSUE TITLE
Support coroutine context for Velocity Brigadier command system

### ISSUE THREAD

**Issue by Distractic** [Shynixn/MCCoroutine#94]
# Context

Currently, for Velocity, the class `SuspendingSimpleCommand` is present. However, lot of server use Brigadier command system.
So, could you add some extensions to use brigadier command in a coroutine context ?

[The documentation about brigadier + Example](https://docs.papermc.io/velocity/dev/command-api)
[Other example of brigadier](https://gist.github.com/4drian3d/8b8db7bd01d2c7b4f8a7e4744620afbc)

**Comment by Shynixn** [comment]
I think the velocity module has got a binding for the brigadier command builder. It is attached to the ``ArgumentBuilder``

https://github.com/Shynixn/MCCoroutine/blob/5453248116100463dc20aa9b2e45f66d5d398e38/mccoroutine-velocity-api/src/main/java/com/github/shynixn/mccoroutine/velocity/MCCoroutine.kt#L103

**Comment by Distractic** [comment]
Ah yes !  My bad,  I didn't see the method `executesSuspend`
