### ISSUE TITLE
Canceling

### ISSUE THREAD

**Issue by Nopock** [Shynixn/MCCoroutine#96]
How does it work with canceling events and still maintain async?

**Comment by Shynixn** [comment]
https://shynixn.github.io/MCCoroutine/wiki/site/faq/#how-to-cancel-suspendable-events

You can cancel before the first suspension point for ordinary events.

For suspendable events fired and awaited by ``PluginManager.callSuspendingEvent`` you can even cancel in the future.

**Comment by Nopock** [comment]
What about setting chat format? after the suspension point?

**Comment by Shynixn** [comment]
Every manipulation of the ``event`` instance after the first suspension point does not change the outcome of the event. The minecraft server simply continous processing after you suspend the event.

**Comment by Shynixn** [comment]
However, if you manipulate async events like ``AsyncPlayerChatEvent``, you are already on an async thread. This means you could use ``runBlocking``  and manipulate the event instance later without any performance problems (you are blocking the async thread, that's fine)
